# Generated by Django 2.0.5 on 2018-05-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180510_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='address',
            field=models.CharField(default='No address', max_length=100),
        ),
    ]
